### ISSUE TITLE
Unequal allocation

### ISSUE THREAD

**Issue by adayim** [begglest/BayesCTDesign#1]
This is an excellent package. I have one question though, the equal allocation is the limitation of the package or it's the method? Many thanks.

**Comment by begglest** [comment]
Alim, Thank you for your interest in BayesCTDesign.  The equal allocation is a limitation of the package.  Expanding the code to allow for unequal allocation is on my to-do list for 2022.

Barry

**Comment by adayim** [comment]
Hi Barry,

Thanks for explaining this. Looking forward to the updated package.

**Comment by JiayiJi** [comment]
Hi Barry,

Thanks for making this excellent package. Do you have time to expand your code to allow for unequal allocation in 2022?

Best,
Jiayi
